### PR TITLE
Crypto payment link integration

### PR DESCRIPTION
**Pull request by JustinCast**
### What does this PR do?
- Enables membership payment with BTC

### CODE REVIEW

**Review by xavier506 — APPROVED** [review]
LGTM

**Comment by AngeloCG97** [comment]
image


Page does not read i18n files

**Comment by AngeloCG97** [comment]
image

If selected the first option button not activated

**Comment by AngeloCG97** [comment]
image

The page doesn't have option to go back homepage, should open in other tab "taget='_blank'"

**Review by AngeloCG97 — CHANGES_REQUESTED** [review]
Please review comments

**Comment by AngeloCG97** [comment]
When the 'Create payment order' button is selected I don't know what happened

**Comment by JustinCast** [comment]
> image
> 
> Page does not read i18n files

@AngeloCG97 actually those plans are not being handled in the i18n config in the actual implementation

**Comment by JustinCast** [comment]
> When the 'Create payment order' button is selected I don't know what happened

I guess there some env vars missing

**Comment by JustinCast** [comment]
@AngeloCG97 @xavier506 how can we configure env vars?
There are a couple of env vars to configure, I can share them with you

**Comment by AngeloCG97** [comment]
> 


The i18n if it is configured and its corresponding files is where those texts are read from.

**Comment by JustinCast** [comment]
> > 
> 
> The i18n if it is configured and its corresponding files is where those texts are read from.

If you go to the actual implementation in the site, you can see that the text is only in Spanish
https://btcnode2.crservers.com/apps/47egazbG6mVHUypcAfMVV67gQSQp/pos

**Comment by AngeloCG97** [comment]
> > > 
> > 
> > 
> > The i18n if it is configured and its corresponding files is where those texts are read from.
> 
> If you go to the actual implementation in the site, you can see that the text is only in Spanish https://btcnode2.crservers.com/apps/47egazbG6mVHUypcAfMVV67gQSQp/pos

This page is from another domain, but the page you develop is included in the asoblockchain.or domain, so you should apply i18n

**Comment by JustinCast** [comment]
> > > > 
> > > 
> > > 
> > > The i18n if it is configured and its corresponding files is where those texts are read from.
> > 
> > 
> > If you go to the actual implementation in the site, you can see that the text is only in Spanish https://btcnode2.crservers.com/apps/47egazbG6mVHUypcAfMVV67gQSQp/pos
> 
> This page is from another domain, but the page you develop is included in the asoblockchain.or domain, so you should apply i18n

Fixed!

**Review by otto-mora — APPROVED** [review]
Make it so. 🖖

**Comment by JustinCast** [comment]
@xavier506 how can see the changes reflected on production?

**Comment by otto-mora** [comment]
> @xavier506 how can see the changes reflected in production?

Created new release. Done-->  https://github.com/edenia/asoblockchain.org/releases/tag/v2.0.6

**Pull request merged**
